<?php
/**
 * Created by PhpStorm.
 * User: Asus
 * Date: 2019/3/1
 * Time: 16:58
 */

namespace im\core\coroutine;

use Swoole\Coroutine\Client as BaseClient;

class CoClient extends BaseClient
{
	public function __construct($args)
	{
		parent::__construct($args);
	}
	
	public function connect($host, $port, $timeout = 0.1)
	{
		return parent::connect($host, $port, $timeout); // TODO: Change the autogenerated stub
	}
	
	public function send($data)
	{
		return parent::send($data); // TODO: Change the autogenerated stub
	}
	
	public function recv()
	{
		return parent::recv(); // TODO: Change the autogenerated stub
	}
	
	public function close()
	{
		return parent::close(); // TODO: Change the autogenerated stub
	}
}